'use client'

import React, { useRef, useEffect, ReactNode } from 'react'
import Image from 'next/image'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism'
import rehypeSlug from 'rehype-slug'
import rehypeAutolinkHeadings from 'rehype-autolink-headings'
import rehypeRaw from 'rehype-raw'
import { MarkdownChart } from '../charts'

interface SimpleMarkdownProps {
  content: string
}

// Detects a ```chart fenced block by inspecting the <pre>'s child <code> node.
// Used to strip the surrounding <pre> so the rendered chart isn't wrapped in
// monospace/preformatted styling.
function isChartNode(node: unknown): boolean {
  if (!node || typeof node !== 'object') return false
  const children = (node as { children?: unknown }).children
  if (!Array.isArray(children)) return false
  const codeNode = children.find(
    (child) => (child as { tagName?: string })?.tagName === 'code',
  ) as { properties?: { className?: unknown } } | undefined
  const className = codeNode?.properties?.className
  return Array.isArray(className) && className.includes('language-chart')
}

interface CodeProps {
  node?: unknown;
  inline?: boolean;
  className?: string;
  children?: ReactNode;
  [key: string]: unknown;
}

// Helper to strip 'node' prop from react-markdown component props
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function stripNode<T extends Record<string, any>>(props: T & { node?: unknown }) {
  const { node, ...rest } = props
  void node
  return rest
}

export const SimpleMarkdown: React.FC<SimpleMarkdownProps> = ({ content }) => {
  const h1CountRef = useRef(0)

  useEffect(() => {
    // Reset counter when content changes
    h1CountRef.current = 0
  }, [content])

  return (
    <div
      className="
        dark:text-white
        dark:bg-zinc-900
        prose prose-neutral dark:prose-invert
        prose-h1:mt-8 prose-h1:mb-4 prose-h1:font-semibold prose-h1:text-3xl
        prose-h2:mt-8 prose-h2:mb-4 prose-h2:font-semibold prose-h2:text-2xl
        prose-h3:mt-8 prose-h3:mb-4 prose-h3:font-semibold prose-h3:text-xl
        prose-code:bg-gray-100 dark:prose-code:bg-gray-800 prose-code:px-2 prose-code:py-1 prose-code:rounded prose-code:break-words
        prose-pre:bg-gray-900 prose-pre:text-gray-100 prose-pre:p-4 prose-pre:rounded-lg prose-pre:overflow-x-auto prose-pre:max-w-full
        max-w-full
        [&_pre]:max-w-full [&_pre]:overflow-x-auto [&_pre]:break-words
        [&_pre_code]:break-words [&_pre_code]:whitespace-pre-wrap [&_pre_code]:word-break-break-all
        [&_code]:break-words [&_code]:max-w-full
      "
    >
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        rehypePlugins={[
          rehypeRaw,
          rehypeSlug,
          [
            rehypeAutolinkHeadings,
            {
              behavior: 'append',
              content: {
                type: 'element',
                tagName: 'a',
                properties: {
                  className: [
                    'text-gray-400',
                    'hover:text-blue-500',
                    'ml-1',
                    'no-underline'
                  ]
                },
                children: [{ type: 'text', value: '' }]
              }
            }
          ]
        ]}
        components={{
          h1: (allProps) => {
            const { children, ...props } = stripNode(allProps)
            h1CountRef.current += 1
            const shouldHide = h1CountRef.current <= 2
            return (
              <h1
                {...props}
                style={shouldHide ? { display: 'none' } : undefined}
                data-markdown-heading="true"
              >
                {children}
              </h1>
            )
          },
          h2(allProps) {
            const props = stripNode(allProps)
            // Keep the unique id generated by rehype-slug. Overriding it with a
            // slug derived only from the text makes duplicate headings (e.g. the
            // many repeated "例句" sections) share the same id, which breaks
            // anchor links and makes the TOC highlight every duplicate at once.
            return <h2 {...props} data-markdown-heading="true" />
          },
          h3(allProps) {
            const props = stripNode(allProps)
            return <h3 {...props} data-markdown-heading="true" />
          },
          table: (allProps) => {
            const { children, ...props } = stripNode(allProps)
            return (
              <div className="not-prose my-6 w-full overflow-x-auto rounded-xl border border-gray-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900/40">
                <table
                  {...props}
                  className="w-full border-collapse text-left text-sm text-gray-700 dark:text-gray-300 [&_tbody_tr]:border-t [&_tbody_tr]:border-gray-100 dark:[&_tbody_tr]:border-zinc-800/70 [&_tbody_tr]:transition-colors [&_tbody_tr:nth-child(even)]:bg-gray-50/60 dark:[&_tbody_tr:nth-child(even)]:bg-zinc-800/30 [&_tbody_tr:hover]:bg-blue-50/60 dark:[&_tbody_tr:hover]:bg-zinc-800/60"
                >
                  {children}
                </table>
              </div>
            )
          },
          thead: (allProps) => {
            const { children, ...props } = stripNode(allProps)
            return (
              <thead
                {...props}
                className="border-b border-gray-200 bg-gray-50 text-gray-900 dark:border-zinc-700 dark:bg-zinc-800 dark:text-gray-100"
              >
                {children}
              </thead>
            )
          },
          th: (allProps) => {
            const { children, ...props } = stripNode(allProps)
            return (
              <th
                {...props}
                className="whitespace-nowrap px-4 py-3 text-left font-semibold"
              >
                {children}
              </th>
            )
          },
          td: (allProps) => {
            const { children, ...props } = stripNode(allProps)
            return (
              <td {...props} className="px-4 py-3 align-top">
                {children}
              </td>
            )
          },
          code: (allProps) => {
            const { inline, className, children, ...props } = stripNode(allProps) as CodeProps
            const match = /language-(\w+)/.exec(className || '')
            // ```chart blocks carry a JSON chart definition; render the graph
            // instead of highlighted source.
            if (!inline && match && match[1] === 'chart') {
              return <MarkdownChart source={String(children)} />
            }
            return !inline && match ? (
              <div className="relative max-w-full overflow-x-auto">
                <SyntaxHighlighter
                  style={oneDark}
                  language={match[1]}
                  PreTag="div"
                  className="max-w-full !my-4"
                  wrapLines={true}
                  wrapLongLines={true}
                  {...props}
                >
                  {String(children).replace(/\n$/, '')}
                </SyntaxHighlighter>
              </div>
            ) : (
              <code className={`${className} break-words max-w-full`} {...props}>
                {children}
              </code>
            )
          },
          pre: (allProps) => {
            const node = (allProps as { node?: unknown }).node
            const { children, ...props } = stripNode(allProps)
            // Charts are block elements already; don't wrap them in <pre>.
            if (isChartNode(node)) {
              return <>{children}</>
            }
            return (
              <pre className="max-w-full overflow-x-auto my-4" {...props}>{children}</pre>
            )
          },
          ul(allProps) {
            const props = stripNode(allProps)
            return <ul className="list-disc pl-8 my-4 space-y-2" {...props} />
          },
          ol(allProps) {
            const props = stripNode(allProps)
            return <ol className="list-decimal pl-8 my-4 space-y-2" {...props} />
          },
          li(allProps) {
            const props = stripNode(allProps)
            return <li className="mb-2" {...props} />
          },
          img(allProps) {
            const { src, alt } = stripNode(allProps)
            // react-markdown / rehype-raw hand us a plain string URL; skip
            // anything else (e.g. blob/empty) that next/image can't optimize.
            if (typeof src !== 'string' || src.length === 0) return null
            // Markdown images carry no intrinsic dimensions, so use next/image's
            // "fill the content width, keep aspect ratio" pattern (width/height 0
            // + sizes). This enables automatic optimization — responsive srcset,
            // lazy loading, and AVIF/WebP — for post photos. The content column
            // maxes out around 864px on desktop and spans the viewport below that.
            return (
              <Image
                src={src}
                alt={typeof alt === 'string' ? alt : ''}
                width={0}
                height={0}
                sizes="(max-width: 1024px) 100vw, 864px"
                className="h-auto w-full rounded-lg"
              />
            )
          },
          iframe(allProps) {
            const { height, className, src, sandbox, ...otherProps } = stripNode(allProps)
            const allowtransparency = !!(allProps as Record<string, unknown>).allowtransparency

            // If height is specified, use it; otherwise use responsive container
            if (height) {
              return (
                <div className={`w-full my-4 ${className || ''}`}>
                  <iframe
                    src={src}
                    height={height}
                    className="w-full rounded-lg"
                    allowFullScreen
                    allowTransparency={allowtransparency}
                    sandbox={sandbox}
                    {...otherProps}
                  />
                </div>
              )
            }

            // Default responsive 16:9 container
            return (
              <div
                className="relative w-full my-4"
                style={{ paddingBottom: '56.25%' }}
              >
                <iframe
                  src={src}
                  className={`absolute top-0 left-0 w-full h-full rounded-lg ${className || ''}`}
                  allowFullScreen
                  allowTransparency={allowtransparency}
                  sandbox={sandbox}
                  {...otherProps}
                />
              </div>
            )
          }
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  )
}
